package com.ghl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2018-10-25T20:03:51.786+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebServiceClient(name = "IHelloService", 
                  wsdlLocation = "http://127.0.0.1:12346/hello?wsdl",
                  targetNamespace = "http://ghl.com/") 
public class IHelloService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ghl.com/", "IHelloService");
    public final static QName IHelloPort = new QName("http://ghl.com/", "IHelloPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:12346/hello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IHelloService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:12346/hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IHelloService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IHelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IHelloService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IHelloService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IHelloService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IHelloService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IHello
     */
    @WebEndpoint(name = "IHelloPort")
    public IHello getIHelloPort() {
        return super.getPort(IHelloPort, IHello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHello
     */
    @WebEndpoint(name = "IHelloPort")
    public IHello getIHelloPort(WebServiceFeature... features) {
        return super.getPort(IHelloPort, IHello.class, features);
    }

}
